ci:
  skip:
    - latexindent-system
    - poetry-lock
    - shfmt-system
repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: "v2.42.1"
    hooks:
      - id: commitizen
  - repo: https://github.com/liblaf/pre-commit-hooks
    rev: "0.2.3"
    hooks:
      - id: latexindent-system
      - id: shfmt-system
  - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: "v2.8.0"
    hooks:
      - id: pretty-format-toml
        args:
          - "--autofix"
        exclude: poetry.lock
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: "v16.0.0"
    hooks:
      - id: clang-format
        args:
          - "--fallback-style"
          - "Google"
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.0.0-alpha.6"
    hooks:
      - id: prettier
        stages:
          - commit
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.4.0"
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-json
      - id: check-symlinks
      - id: check-toml
      - id: check-yaml
      - id: destroyed-symlinks
      - id: end-of-file-fixer
        exclude: requirements.txt
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: "23.3.0"
    hooks:
      - id: black
      - id: black-jupyter
  - repo: https://github.com/PyCQA/isort
    rev: "5.12.0"
    hooks:
      - id: isort
        args:
          - "--profile"
          - "black"
          - "--filter-files"
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: "0.22.0"
    hooks:
      - id: check-dependabot
      - id: check-github-actions
      - id: check-github-workflows
  - repo: https://github.com/python-poetry/poetry
    rev: "1.4.0"
    hooks:
      - id: poetry-check
      - id: poetry-lock
        files: pyproject.toml
      - id: poetry-export
        args:
          - "--output"
          - "requirements.txt"
          - "--without-hashes"
          - "--without-urls"
