words:
  - achemso
  - alph
  - amssymb
  - amsthm
  - auctex
  - beamercolorbox
  - biber
  - ctex
  - cvitems
  - cython
  - detexify
  - dmypy
  - dpth
  - eledsec
  - esint
  - etoolbox
  - expex
  - feynmf
  - feynmp
  - gaux
  - glog
  - glsdefs
  - glstex
  - gomod
  - graphicx
  - gtex
  - gummi
  - htlatex
  - iarticle
  - ibeamer
  - icode
  - ifstrempty
  - ipynb
  - iwork
  - kile
  - knitr
  - kpsewhich
  - kvoptions
  - latexmk
  - liblaf
  - ltjruby
  - luatexja
  - lxml
  - mathrsfs
  - mkdocs
  - nofootinbib
  - noitemsep
  - nolinkurl
  - pdfpc
  - pdfpcnotes
  - pybuilder
  - pycache
  - pyflow
  - pypa
  - pypackages
  - pytxcode
  - pytype
  - rsfs
  - runin
  - scmd
  - scrwfile
  - setbeamercolor
  - siunitx
  - sout
  - sympy
  - tabularx
  - tcbox
  - tcolorbox
  - texmfhome
  - texmflocal
  - texpadtmp
  - theid
  - thmtools
  - typer
  - vhistory
  - wysiwym
  - xcolor
  - xindy
  - xkeyval
  - xmpi
  - xnic
  - xparse
  - xwatermark
  - xypic
ignorePaths:
  - "*-lock.*"
  - "*.lock"
dictionaries:
  - bash
  - cpp
  - cpp-refined
  - dotnet
  - en-gb
  - fonts
  - fullstack
  - latex
  - makefile
  - npm
  - python
  - python-common
allowCompoundWords: true
