packages:
  - amsmath
  - amssymb
  - amsthm
  - array
  - babel
  - blindtext
  - booktabs
  - caption
  - cleveref
  - enumitem
  - esint
  - etoolbox
  - fancyhdr
  - float
  - fontspec
  - geometry
  - graphicx
  - hyperref
  - import
  - lastpage
  - lipsum
  - mathtools
  - microtype
  - multicol
  - multirow
  - mwe
  - physics
  - siunitx
  - subcaption
  - tabularx
  - tasks
  - tcolorbox
  - ulem
  - xcolor
  - xkeyval
  - xparse
