name: Documentation

on:
  push:
    branches:
      - main

permissions:
  contents: write

env:
  PYTHON_VERSION: 3.x

jobs:
  docs:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup TeX Live
        run: |-
          sudo apt update
          sudo apt install fonts-noto fonts-noto-cjk texlive-full
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: pip
          cache-dependency-path: docs/requirements.txt
      - name: Install Python Dependencies
        run: pip install --requirement docs/requirements.txt
      - name: Deploy to GitHub Pages
        run: make --jobs docs-gh-deploy
